work_dir: C:\\Users\\cleison.c.amorim\\Downloads\\mestrado\\workdir
metadata_file: C:\\Users\\cleison.c.amorim\\Downloads\\mestrado\\workdir\\dai-asllvd.xlsx
clean_workdir: False

phases:  
  filter,
  split,
  normalize

download:
  output_dir: ../../original
  url: http://csr.bu.edu/ftp/asl/asllvd/asl-data2/quicktime
  file_pattern: '{session}/scene{scene}-camera{camera}.mov'
  metadata_url: http://www.bu.edu/asllrp/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx

segment:
  input_dir: ../../original
  output_dir: segmented
  fps_in: 60
  fps_out: 30

skeleton:
  openpose:   /home/student/dl2/grp5/cca5/openpose/openpose/build
  input_dir: ./segmented
  output_dir: ./skeleton
  model_path: ./st-gcn/models

filter:
  input_dir: ./skeleton
  output_dir: ./filtered
  points: 1, 2, 3, 5, 6,
          88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
          109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129

split:
  input_dir: ./filtered
  output_dir: ./splitted
  test: 20
  val: 0
  seed: 2

normalize:
  input_dir: ./splitted
  output_dir: ./normalized
  joints: 27
  channels: 3
  num_person: 1
  repeat_frames: True
  max_frames: 63

debug_opts:
  download_items: 5
  split_items: 5
  pose_items: 5
  gendata_items: 5
  gendata_joints: 27