input_dir:  /home/cleison/Documentos/dataset-20/original
work_dir:   /home/cleison/Documentos/dataset-20/workdir
output_dir: /home/cleison/Documentos/dataset-20/preprocessed
openpose:   /home/cleison/Documentos/OpenPose/openpose/build
metadata_file:  /home/cleison/Documentos/dataset-20/dai-asllvd-20.xlsx
clean_workdir: False

phases: 
  #download, 
  #split, 
  # pose, 
  holdout,
  gendata

holdout:
  test: 33
  val: 0
  seed: 2

download:
  url: http://csr.bu.edu/ftp/asl/asllvd/asl-data2/quicktime
  file_pattern: '{session}/scene{scene}-camera{camera}.mov'
  metadata_url: http://www.bu.edu/asllrp/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx

split:
  fps_in: 60
  fps_out: 30

gendata:
  joints: 130
  channels: 3
  num_person: 1
  repeat_frames: True
  max_frames: 60

debug_opts:
  download_items: 5
  split_items: 5
  pose_items: 5
  gendata_items: 5
  gendata_joints: 18