weights: /media/sdb1/recognition/LAST/epoch630_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /media/sdb1/dataset/preprocessing/test_data.npy
  label_path: /media/sdb1/dataset/preprocessing/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2745
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl' 
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 32
