work_dir: /home/student/dl4/ca/workdir/recognition/LAST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: False
  window_size: 60
  data_path: /home/student/dl4/ca/workdir/normalized/train_data.npy 
  label_path: /home/student/dl4/ca/workdir/normalized/train_label.pkl
test_feeder_args:
  data_path: /home/student/dl4/ca/workdir/normalized/test_data.npy
  label_path: /home/student/dl4/ca/workdir/normalized/test_label.pkl

log_interval: 25

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 20
  edge_importance_weighting: True
  graph_args:
    layout: 'custom'
    strategy: 'spatial'
    custom_layout:
      num_node: 47
      center: 0
      edge: (0, 1), (1, 2), (2, 26),
            (0, 3), (3, 4), (4, 5),
            (5, 6), (6, 7), (7, 8), (8, 9),
            (5, 10), (10, 11), (11, 12), (12, 13),
            (5, 14), (14, 15), (15, 16), (16, 17),
            (5, 18), (18, 19), (19, 20), (20, 21),
            (5, 22), (22, 23), (23, 24), (24, 25),
            (26, 27), (27, 28), (28, 29), (29, 30),
            (26, 31), (31, 32), (32, 33), (33, 34),
            (26, 35), (35, 36), (36, 37), (37, 38),
            (26, 39), (39, 40), (40, 41), (41, 42),
            (26, 43), (43, 44), (44, 45), (45, 46),
            (7, 9), (11, 13), (15, 17), (19, 21), (23, 25),
            (9, 10), (13, 14), (17, 18), (21, 22), (25, 18),
            (30, 32), (34, 35), (38, 39), (42, 43), (46, 39),
            (7, 24), (11, 24), (15, 24), (19, 24),
            (28, 45), (32, 45), (36, 45), (40, 45)


# training
device: [0]
batch_size: 8
test_batch_size: 8

#optim
optimizer: SGD
nesterov: True
base_lr: 0.01
step: [50, 100, 150]
num_epoch: 200
