work_dir: ./work_dir/recognition/sl/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 126
  data_path: /home/cleison/Documentos/dataset/preprocessed/train_data.npy 
  label_path: /home/cleison/Documentos/dataset/preprocessed/train_label.pkl
test_feeder_args:
  data_path: /home/cleison/Documentos/dataset/preprocessed/test_data.npy
  label_path: /home/cleison/Documentos/dataset/preprocessed/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 49 #400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose' #'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 8 #256 
test_batch_size: 5 #256

#optim
base_lr: 0.1
step: [300, 500, 650, 800]
num_epoch: 1000



