work_dir: /home/student/dl2/grp5/cca5/dataset/recognition/LAST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: False
  window_size: 60
  data_path: /home/student/dl2/grp5/cca5/dataset/preprocessed/train_data.npy 
  label_path: /home/student/dl2/grp5/cca5/dataset/preprocessed/train_label.pkl
test_feeder_args:
  data_path: /home/student/dl2/grp5/cca5/dataset/preprocessed/test_data.npy
  label_path: /home/student/dl2/grp5/cca5/dataset/preprocessed/test_label.pkl

log_interval: 25

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 20
  edge_importance_weighting: True
  graph_args:
    layout: 'custom'
    strategy: 'spatial'
    custom_layout:
      num_node: 27
      center: 0
      edge: (0, 1), (1, 2), (2, 12) 
            (0, 3), (3, 4), (4, 5),
            (5, 6), (6, 7),
            (5, 8), (8, 9),
            (5, 10), (10, 11),
            (5, 12), (12, 13),
            (5, 14), (14, 15),
            (12, 13), (13, 14),
            (12, 15), (15, 16),
            (12, 17), (17, 18),
            (12, 19), (19, 20),
            (12, 21), (21, 22)

# training
device: [0]
batch_size: 8
test_batch_size: 8

#optim
optimizer: SGD
nesterov: True
base_lr: 0.01
step: [50, 100, 150, 200]
num_epoch: 300
