input_dir:  /home/cleison/Documentos/dataset/original
work_dir:   /home/cleison/Documentos/dataset/workdir
output_dir: /home/cleison/Documentos/dataset/preprocessed
openpose:   /home/cleison/Documentos/OpenPose/openpose/build
metadata_file:  /home/cleison/Documentos/dataset/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx
clean_workdir: False

phases: 
  # download, 
  # split, 
  # pose, 
  holdout,
  gendata

holdout:
  test: 20
  val: 0
  seed: 1

download:
  url: http://csr.bu.edu/ftp/asl/asllvd/asl-data2/quicktime
  file_pattern: '{session}/scene{scene}-camera{camera}.mov'
  metadata_url: http://www.bu.edu/asllrp/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx

split:
  fps_in: 60
  fps_out: 30

gendata:
  joints: 130
  channels: 3
  num_person: 1
  repeat_frames: True
  max_frames: 63


debug_opts:
  download_items: 10
  split_items: 100
  pose_items: 100
  gendata_items: 100
  gendata_joints: 18