input_dir:  /home/cca5/documents/dataset/original
work_dir:   /home/cca5/documents/dataset/workdir
output_dir: /home/cca5/documents/dataset/preprocessing
openpose:   /home/cca5/documents/openpose/build
metadata_file:  /home/cca5/documents/dataset/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx
clean_workdir: False
max_frames: 130

phases:
  download,
  split,
  pose,
  holdout,
  gendata

holdout:
  test: 15
  val: 15

download:
  url: http://csr.bu.edu/ftp/asl/asllvd/asl-data2/quicktime
  file_pattern: '{session}/scene{scene}-camera{camera}.mov'
  metadata_url: http://www.bu.edu/asllrp/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx

split:
  fps_in: 60
  fps_out: 30

gendata:
  joints: 130
  channels: 3
  num_person: 1
  repeat_frames: True

debug_opts:
  download_items: 3
  split_items: 20
  pose_items: 20
  gendata_joints: 18
