weights: ./models/kinetics-st_gcn.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /home/cleison/Documentos/dataset/gendata/val_data.npy
  label_path: /home/cleison/Documentos/dataset/gendata/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 103 #400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl' #'openpose'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64
