weights: /home/documents/recognition-20/LAST/epoch600_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /home/documents/dataset-20/preprocessing/test_data.npy
  label_path: /home/documents/dataset-20/preprocessing/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 20
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl' 
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 16
