work_dir: /media/sdb1/recognition/LAST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 63
  data_path:  /media/sdb1/dataset/preprocessing/train_data.npy
  label_path: /media/sdb1/dataset/preprocessing/train_label.pkl
test_feeder_args:
  data_path:  /media/sdb1/dataset/preprocessing/val_data.npy
  label_path: /media/sdb1/dataset/preprocessing/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2745
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl'
    strategy: 'spatial'

# training
device: [0]
batch_size: 32 
test_batch_size: 32

#optim
base_lr: 0.1
step: [400, 700, 800, 900]
num_epoch: 1000



