work_dir: /documents/recognition-20/LAST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 126
  data_path: /home/documents/dataset-20/preprocessing/train_data.npy 
  label_path: /home/documents/dataset-20/preprocessing/train_label.pkl
test_feeder_args:
  data_path: /home/documents/dataset-20/preprocessing/test_data.npy
  label_path: /home/documents/dataset-20/preprocessing/test_label.pkl

log_interval: 25

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 20
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl'
    strategy: 'spatial'

# training
device: [0]
batch_size: 24
test_batch_size: 24

#optim
base_lr: 0.1
step: [200, 300, 400, 500]
num_epoch: 60



