work_dir: /home/cleison/Documentos/dataset-20/recognition/LAST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 126
  data_path: /home/cleison/Documentos/dataset-20/preprocessing/train_data.npy 
  label_path: /home/cleison/Documentos/dataset-20/preprocessing/train_label.pkl
test_feeder_args:
  data_path: /home/cleison/Documentos/dataset-20/preprocessing/val_data.npy
  label_path: /home/cleison/Documentos/dataset-20/preprocessing/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 20
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl'
    strategy: 'spatial'

# training
device: [0]
batch_size: 8 
test_batch_size: 8

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 60



