work_dir: /home/documents/recognition/LAST
start_epoch: 630
weights: /home/documents/recognition/LAST/epoch630_model.pt

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 63
  data_path:  /home/documents/dataset/preprocessed/train_data.npy
  label_path: /home/documents/dataset/preprocessed/train_label.pkl

test_feeder_args:
  data_path:  /home/documents/dataset/preprocessing/test_data.npy
  label_path: /home/documents/dataset/preprocessing/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2745
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose-sl'
    strategy: 'spatial'

# training
device: [0]
batch_size: 32 
test_batch_size: 32

#optim
base_lr: 0.1
step: [400, 700, 800, 900]
num_epoch: 1000


