# command line: main.py preprocessing --config config/preproc-hg.yaml

clean_workdir: false
config: config/preproc-hg.yaml
debug: false
debug_opts:
    download_items: 5
    gendata_items: 5
    gendata_joints: 27
    pose_items: 5
    split_items: 5
download:
    file_pattern: '{session}/scene{scene}-camera{camera}.mov'
    metadata_url: http://www.bu.edu/asllrp/dai-asllvd-BU_glossing_with_variations_HS_information-extended-urls-RU.xlsx
    output_dir: ../../original
    url: http://csr.bu.edu/ftp/asl/asllvd/asl-data2/quicktime
filter:
    input_dir: ./skeleton
    output_dir: ./filtered
    points: 1, 2, 3, 5, 6, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129
input_dir: null
metadata_file: C:\\Users\\cleison.c.amorim\\Downloads\\mestrado\\workdir\\dai-asllvd.xlsx
normalize:
    channels: 3
    input_dir: ./splitted
    joints: 27
    max_frames: 63
    num_person: 1
    output_dir: ./normalized
    repeat_frames: true
output_dir: null
phases:
- filter
- split
- normalize
print_log: true
save_log: true
segment:
    fps_in: 60
    fps_out: 30
    input_dir: ../../original
    output_dir: segmented
skeleton:
    input_dir: ./segmented
    model_path: ./st-gcn/models
    openpose: /home/student/dl2/grp5/cca5/openpose/openpose/build
    output_dir: ./skeleton
split:
    input_dir: ./filtered
    output_dir: ./splitted
    seed: 2
    test: 20
    val: 0
work_dir: C:\\Users\\cleison.c.amorim\\Downloads\\mestrado\\workdir
